### ISSUE TITLE
关于源IP哈希的文档疑惑

### ISSUE THREAD

**Issue by Triple-Z** [huaweicloudDocs/elb#1]
> 源IP算法：将请求的源IP地址进行Hash运算，得到一个具体的数值，同时对后端服务器进行编号，按照运算结果将请求分发到对应编号的服务器上。这可以使得对不同源IP的访问进行负载分发，同时使得同一个客户端IP的请求始终被派发至某特定的服务器。该方式适合负载均衡无cookie功能的TCP协议。

请问这个源 IP 算法是一致性哈希的么？

https://github.com/huaweicloudDocs/elb/blob/master/cn.zh-cn/%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/%E6%B5%81%E9%87%8F%E5%88%86%E9%85%8D%E7%AD%96%E7%95%A5.md

**Comment by adams-info** [comment]
这个源IP算法是一致性哈希。
